-- PROJECT_TASK seed data with ASSIGNEE_ID
-- Sprint IDs: 1=Sprint0, 2=Sprint1, 3=Sprint2  |  PROJECT_ID=2
--
-- Employee IDs:
--   5  = Diego Angulo  (a01644350@tec.mx)
--   6  = Diego Ibarra  (A01643797@tec.mx)
--   7  = Ivanna Banderas (A01638966@tec.mx)
--   8  = Maria Jose Medina (A01639205@tec.mx)
--   9  = Gael Castillo  (A01638638@tec.mx)
--   10 = Eugenio Loeza  (A01067846@tec.mx)

-- ===== SPRINT 1 (Sprint 0 in Excel) =====
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Definicion de la arquitectura de sistema', 'done', 'high', 15, 5, 5, TO_DATE('2026-02-09', 'YYYY-MM-DD'), TO_DATE('2026-02-11', 'YYYY-MM-DD'), TO_DATE('2026-02-11', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Integracion inicial con Telegram', 'done', 'medium', 10, 3, 3, TO_DATE('2026-02-23', 'YYYY-MM-DD'), TO_DATE('2026-02-26', 'YYYY-MM-DD'), TO_DATE('2026-02-26', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Definicion del backend', 'done', 'high', 10, 6, 6, TO_DATE('2026-02-12', 'YYYY-MM-DD'), TO_DATE('2026-02-14', 'YYYY-MM-DD'), TO_DATE('2026-02-14', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Definicion de KPIs del sistema', 'done', 'medium', 15, 2, 2, TO_DATE('2026-02-19', 'YYYY-MM-DD'), TO_DATE('2026-02-20', 'YYYY-MM-DD'), TO_DATE('2026-02-20', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 5, 'Modelado de base de datos', 'done', 'high', 15, 4, 4, TO_DATE('2026-02-15', 'YYYY-MM-DD'), TO_DATE('2026-02-18', 'YYYY-MM-DD'), TO_DATE('2026-02-18', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 10, 'Configuracion del repositorio', 'done', 'high', 5, 1, 1, TO_DATE('2026-02-21', 'YYYY-MM-DD'), TO_DATE('2026-02-22', 'YYYY-MM-DD'), TO_DATE('2026-02-22', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, NULL, 'Cursos- Linux- Ivanna', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, NULL, 'Cursos- Linux- Maria Jose', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 9, 'Cursos- Linux- Gael', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Cursos- Linux- Diego I', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 5, 'Cursos- Linux- Diego A', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 10, 'Cursos- Linux- Eugenio', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, NULL, 'Cursos- Oracle- Ivanna', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, NULL, 'Cursos- Oracle- Maria Jose', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 9, 'Cursos- Oracle- Gael', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 6, 'Cursos- Oracle- Diego I', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 5, 'Cursos- Oracle- Diego A', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (1, 2, 10, 'Cursos- Oracle- Eugenio', 'done', 'low', 15, 4, 4, TO_DATE('2026-02-24', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'), TO_DATE('2026-02-13', 'YYYY-MM-DD'));

-- ===== SPRINT 2 (Sprint 1 in Excel) =====
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Refinamiento análisis de KPIs del sprint', 'done', 'medium', 15, 3, 3, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Refinamiento de requerimientos implementados en el Sprint 0', 'done', 'high', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Refinamiento de diseño de arquitectura implementada en el Sprint 0', 'done', 'high', 15, 3, 3, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Refinamiento de base de datos implementada en el Sprint 0', 'done', 'high', 10, 3, 3, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Reunión semanal', 'done', 'medium', 5, 1, 1, TO_DATE('2026-04-05', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Implementar CommentController con endpoints CRUD', 'done', 'high', 15, 5, 5, TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2026-03-02', 'YYYY-MM-DD'), TO_DATE('2026-03-02', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Implementar EmployeeController con endpoints CRUD', 'done', 'high', 10, 3, 3, TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2026-03-02', 'YYYY-MM-DD'), TO_DATE('2026-03-02', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Implementar ProjectController con endpoints CRUD', 'done', 'high', 15, 5, 5, TO_DATE('2026-03-02', 'YYYY-MM-DD'), TO_DATE('2026-03-03', 'YYYY-MM-DD'), TO_DATE('2026-03-03', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Implementar SprintController con endpoints CRUD', 'done', 'high', 15, 4, 4, TO_DATE('2026-03-02', 'YYYY-MM-DD'), TO_DATE('2026-03-03', 'YYYY-MM-DD'), TO_DATE('2026-03-03', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Implementar TaskController con endpoints CRUD', 'done', 'high', 15, 5, 5, TO_DATE('2026-03-03', 'YYYY-MM-DD'), TO_DATE('2026-03-04', 'YYYY-MM-DD'), TO_DATE('2026-03-04', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Implementar TelegramBotController para notificaciones', 'done', 'medium', 10, 4, 4, TO_DATE('2026-03-03', 'YYYY-MM-DD'), TO_DATE('2026-03-04', 'YYYY-MM-DD'), TO_DATE('2026-03-04', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 7, 'Crear página Dashboard con métricas principales', 'done', 'medium', 15, 6, 6, TO_DATE('2026-04-04', 'YYYY-MM-DD'), TO_DATE('2026-04-04', 'YYYY-MM-DD'), TO_DATE('2026-04-04', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 7, 'Crear página de Proyectos con listado y detalles', 'done', 'medium', 10, 3, 3, TO_DATE('2026-04-04', 'YYYY-MM-DD'), TO_DATE('2026-04-04', 'YYYY-MM-DD'), TO_DATE('2026-04-04', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Crear página de Sprints con visualización de estado', 'done', 'medium', 10, 4, 4, TO_DATE('2026-04-05', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Implementar tablero Kanban con drag-and-drop', 'done', 'high', 15, 5, 5, TO_DATE('2026-04-06', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Desarrollar TaskModal con pestañas (Detalles, Asignados, Comentarios)', 'done', 'medium', 10, 4, 4, TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 7, 'Implementar visualización de estado de tareas', 'done', 'high', 10, 2, 2, TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-07', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Configurar autenticación JWT en backend', 'done', 'high', 10, 2, 2, TO_DATE('2026-03-29', 'YYYY-MM-DD'), TO_DATE('2026-04-02', 'YYYY-MM-DD'), TO_DATE('2026-04-02', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Implementar login con manejo de tokens', 'done', 'high', 10, 3, 3, TO_DATE('2026-03-29', 'YYYY-MM-DD'), TO_DATE('2026-03-30', 'YYYY-MM-DD'), TO_DATE('2026-03-30', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Implementar refresh de token', 'done', 'high', 10, 3, 3, TO_DATE('2026-03-30', 'YYYY-MM-DD'), TO_DATE('2026-03-30', 'YYYY-MM-DD'), TO_DATE('2026-03-30', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Crear roles de usuario (Manager, Developer)', 'done', 'high', 5, 1, 1, TO_DATE('2026-03-31', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Restringir rutas con ProtectedRoute', 'done', 'high', 10, 2, 2, TO_DATE('2026-03-31', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Implementar dashboard de KPIs para Manager', 'done', 'medium', 15, 7, 7, TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 7, 'Implementar dashboard de KPIs para Developer', 'done', 'medium', 10, 4, 4, TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Mostrar tasa de finalización de tareas en dashboard', 'done', 'medium', 10, 2, 2, TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Mostrar tiempo invertido por developer', 'done', 'medium', 10, 2, 2, TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'), TO_DATE('2026-04-08', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Mostrar distribucion de trabajo', 'done', 'medium', 10, 2, 2, TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Mostrar el promedio de finalización de tareas', 'done', 'high', 10, 2, 2, TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Implementar asignación de tareas a usuarios', 'done', 'high', 10, 2, 2, TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Implementar asignación de miembros a proyectos', 'done', 'medium', 10, 2, 2, TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Implementar consulta de tareas asignadas', 'done', 'medium', 10, 2, 2, TO_DATE('2026-04-07', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Implementar vista de backlog', 'done', 'low', 10, 2, 2, TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'), TO_DATE('2026-04-09', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Empaquetar aplicación en archivo .tar', 'done', 'low', 5, 1, 1, TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Transferir archivo a OCI', 'done', 'medium', 5, 1, 1, TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Actualizar proxy de Vite para nuevas rutas', 'done', 'high', 5, 1, 1, TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Definir esquemas Hibernate (EmployeeTask, EmployeeTeam)', 'done', 'high', 10, 2, 2, TO_DATE('2026-03-26', 'YYYY-MM-DD'), TO_DATE('2026-03-27', 'YYYY-MM-DD'), TO_DATE('2026-03-27', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Configurar relaciones entre entidades', 'done', 'high', 10, 3, 3, TO_DATE('2026-03-27', 'YYYY-MM-DD'), TO_DATE('2026-03-28', 'YYYY-MM-DD'), TO_DATE('2026-03-28', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Refinar estructura de base de datos', 'done', 'high', 15, 4, 4, TO_DATE('2026-03-28', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Implementar capa API (lib/api.js)', 'done', 'high', 10, 4, 4, TO_DATE('2026-04-03', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Corregir errores en login y autenticación', 'done', 'low', 10, 2, 2, TO_DATE('2026-04-04', 'YYYY-MM-DD'), TO_DATE('2026-04-06', 'YYYY-MM-DD'), TO_DATE('2026-04-06', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 7, 'Cursos- Oracle- Ivanna', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 8, 'Cursos- Oracle- Maria Jose', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 9, 'Cursos- Oracle- Gael', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 6, 'Cursos- Oracle- Diego I', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 5, 'Cursos- Oracle- Diego A', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (2, 2, 10, 'Cursos- Oracle- Eugenio', 'done', 'low', 15, 5, 5, TO_DATE('2026-03-23', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'));

-- ===== SPRINT 3 (Sprint 2 in Excel) =====
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 7, 'Cursos- Oracle- Ivanna', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 8, 'Cursos- Oracle- Maria Jose', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 9, 'Cursos- Oracle- Gael', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 6, 'Cursos- Oracle- Diego I', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 5, 'Cursos- Oracle- Diego A', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 10, 'Cursos- Oracle- Eugenio', 'in_progress', 'low', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 5, 'Implementar validación de seguridad en queries (evitar accesos indebidos)', 'in_progress', 'high', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 10, 'Implementar logs de consultas', 'done', 'medium', 10, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 10, 'Definir métricas individuales por desarrollador', 'done', 'high', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 7, 'Calcular tasa de completitud por usuario', 'in_progress', 'high', 10, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 9, 'Calcular tiempo promedio por tarea por usuario', 'done', 'high', 5, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 9, 'Implementar tracking de tareas actualizadas por usuario (visibilidad)', 'todo', 'high', 5, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 8, 'Mostrar KPIs individuales en dashboard de Developer', 'in_progress', 'high', 15, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 8, 'Implementar comparación de desempeño entre miembros', 'in_progress', 'medium', 10, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (3, 2, 9, 'Registrar actividad de usuario (updates, cambios de estado)', 'done', 'medium', 10, NULL, NULL, NULL, NULL, NULL);

COMMIT;
