-- Sprint 3 CI/CD Pipeline Tasks
-- Sprint ID: 21 (Sprint 3) | PROJECT_ID=2
--
-- Objetivo: Automatizar deployment con GitHub Actions + OCI (Terraform & K8s)
--
-- Employee IDs & Roles (from DB):
--   82 = Diego Angulo   - UI/UX Design & QA Specialist
--   21 = Diego Ibarra   - Tech Lead & DevOps Software Engineer
--   83 = Ivanna Banderas - Database Management
--   81 = Maria Jose Medina - Backend Developer
--   61 = Gael Castillo  - Scrum Master & Manager
--   84 = Eugenio Loeza  - Frontend Developer

-- ===== SPRINT 21 (Sprint 3) - CI/CD Pipelines =====

-- === INFRAESTRUCTURA Y CONFIGURACIÓN BASE (Tech Lead & DevOps - Diego Ibarra) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 21, 'Configurar secrets de OCI en GitHub (OCIR credentials, OKE kubeconfig, Terraform vars)', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 21, 'Crear workflow base de GitHub Actions con runners (GitHub-hosted o OCI self-hosted)', 'todo', 'high', 15, 5, NULL, NULL, NULL, NULL);

    INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
    VALUES (21, 1, 21, 'Configurar OCI CLI y kubectl en el runner de GitHub Actions', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 21, 'Crear pipeline de Terraform plan/apply automatizado en GitHub Actions', 'todo', 'high', 15, 6, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 21, 'Diseñar estrategia de branching y triggers para pipelines (main, develop, feature/*)', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 21, 'Definir environments (staging/production) en GitHub con protección de branches', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

-- === PIPELINE BACKEND CI/CD (Backend Developer - Maria Jose) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 81, 'Crear workflow CI backend: Maven build + tests en cada PR', 'todo', 'high', 15, 5, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 81, 'Crear workflow CD backend: Docker build + push a OCIR en merge a main', 'todo', 'high', 15, 5, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 81, 'Automatizar deploy a OKE (kubectl apply) post-push de imagen al registry', 'todo', 'high', 15, 5, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 81, 'Implementar rollback automático en caso de fallo de deployment', 'todo', 'medium', 10, 4, NULL, NULL, NULL, NULL);

-- === PIPELINE FRONTEND CI (Frontend Developer - Eugenio) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 84, 'Crear workflow CI frontend: npm install + lint + build en cada PR', 'todo', 'high', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 84, 'Configurar cache de node_modules en GitHub Actions para frontend', 'todo', 'medium', 5, 2, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 84, 'Integrar build de frontend en el pipeline de Docker (multi-stage con Vite)', 'todo', 'high', 10, 4, NULL, NULL, NULL, NULL);

-- === DATABASE MANAGEMENT & TERRAFORM STATE (Database - Ivanna) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 83, 'Implementar Terraform state backend en OCI Object Storage para CI', 'todo', 'high', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 83, 'Crear workflow para ejecutar migraciones de BD automaticamente post-deploy', 'todo', 'high', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 83, 'Migrar variables de env.sh y state-functions a GitHub Secrets/Variables', 'todo', 'high', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 83, 'Crear template de K8s manifest con envsubst para reemplazar variables en CI', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

-- === QA Y VALIDACIÓN DE PIPELINES (UI/UX & QA - Diego Angulo) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 82, 'Crear workflow de validación de código (linting + format check) como gate en PRs', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 82, 'Crear workflow de health-check post-deploy para validar servicio activo', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 82, 'Implementar notificaciones de pipeline (Telegram) en caso de fallo o éxito', 'todo', 'medium', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 82, 'Documentar pipelines en README con diagrama de flujo CI/CD', 'todo', 'medium', 10, 4, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 82, 'Implementar badge de status del pipeline en README del repositorio', 'todo', 'low', 5, 1, NULL, NULL, NULL, NULL);

-- === GESTIÓN Y SUPERVISIÓN (Scrum Master - Gael) ===

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 61, 'Definir criterios de aceptación y DoD para cada pipeline', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 61, 'Configurar branch protection rules y required checks en GitHub', 'todo', 'high', 10, 2, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 61, 'Crear workflow de integration tests end-to-end post-deploy', 'todo', 'high', 15, 6, NULL, NULL, NULL, NULL);

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (21, 1, 61, 'Validar y aprobar pipelines completos en ambiente staging antes de prod', 'todo', 'high', 10, 3, NULL, NULL, NULL, NULL);

COMMIT;
