-- Sprint 3 Task Seeds — PROJECT_ID=2, SPRINT_ID=61
--
-- Employee IDs (PROJECT_ID=2):
--   5  = Diego Angulo   — QA Specialist
--   6  = Diego Ibarra   — Tech Lead & DevOps
--   7  = Ivanna Banderas — Database Management
--   8  = Maria Jose Medina — Backend Developer
--   9  = Gael Castillo  — Scrum Master & Manager
--   10 = Eugenio Loeza  — Frontend Developer

-- === Oracle Courses (each person assigned to their own) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 7, 'Cursos- Oracle- Ivanna', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Cursos- Oracle- Maria Jose', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Cursos- Oracle- Gael', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 6, 'Cursos- Oracle- Diego I', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Cursos- Oracle- Diego A', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Cursos- Oracle- Eugenio', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- === Testing Tasks (Diego Angulo — QA Specialist) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Creacion de pruebas blackbox', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Creacion de pruebas de integracion', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-06', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Creacion de pruebas de funcionalidades', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-06', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Creacion de pruebas de flujo de control', 'done', 'medium', 4, 4, 4, TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- === Deliverables ===
-- User manual for Project Admin class — Diego Angulo (UX/QA, knows user flows best)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Entregable Project Admin-Israel (Manual de usuarios)', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Database deliverable — Ivanna (Database Management)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 7, 'Entreagble Base de Datos-Sacnite', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Requirements deliverable — Diego Angulo (led requirements in prior sprints)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Entregable Requerimientos-Sacnite', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Software Quality deliverable — Diego Angulo (QA Specialist)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Entregable Software Quality- Mike', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Design & Architecture deliverable — Diego Ibarra (Tech Lead)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 6, 'Entrega Design and Architecture- Paco', 'done', 'medium', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- === Bug Fixes & Backend Changes ===
-- Backend duplicate-name bug — Maria Jose (Backend Developer)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Corregir errores en duplicacion de nombres en sprints y proyectos', 'done', 'high', 3, 3, 3, TO_DATE('2026-04-28', 'YYYY-MM-DD'), TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-04', 'YYYY-MM-DD'));

-- Required fields validation — Diego Angulo (QA)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Revisar campos obligatorios en creacion de Task, Sprints y Proyectos', 'done', 'medium', 2, 2, 2, TO_DATE('2026-04-30', 'YYYY-MM-DD'), TO_DATE('2026-05-05', 'YYYY-MM-DD'), TO_DATE('2026-05-05', 'YYYY-MM-DD'));

-- Remove Sprint start/end/pause UI — Eugenio (Frontend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Eliminar funcionalidades de start, end and pause en Sprint', 'done', 'low', 3, 3, 3, TO_DATE('2026-04-30', 'YYYY-MM-DD'), TO_DATE('2026-05-05', 'YYYY-MM-DD'), TO_DATE('2026-05-05', 'YYYY-MM-DD'));

-- Activity logging in app — Maria Jose (Backend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Registrar actividades de los usuarios en la aplicacion', 'done', 'high', 3, 3, 3, TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-07', 'YYYY-MM-DD'), TO_DATE('2026-05-07', 'YYYY-MM-DD'));

-- Sprint/Backlog control flow review — Diego Angulo (QA)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Revisar flujo de control entre Sprint y Backloag', 'done', 'medium', 3, 3, 3, TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-08', 'YYYY-MM-DD'));

-- === Story Points Tracking ===
-- Excel tracking — Gael (Scrum Master)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Registrar los story points en Excel', 'done', 'high', 2, 2, 2, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

-- In-app story points — Maria Jose (Backend data model)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Registrar los story points en la aplicacion', 'done', 'high', 3, 3, 3, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

-- === OCI & Sprint Ceremony ===
-- OCI cost check — Diego Ibarra (DevOps)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 6, 'Verificar gastos en OCI', 'done', 'low', 1, 1, 1, TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Sprint presentation — Gael (Scrum Master)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Preparar presentacion Sprint 3', 'done', 'medium', 4, 4, 4, TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- === Permissions & Security ===
-- User role restriction for tasks — Maria Jose (Backend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Permitir que Users únicamente puedan crear y gestionar tareas.', 'done', 'high', 3, 3, 3, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_DATE('2026-05-12', 'YYYY-MM-DD'));

-- Backend permission validation — Diego Ibarra (Tech Lead)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 6, 'Validar permisos desde backend.', 'done', 'medium', 3, 3, 3, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-13', 'YYYY-MM-DD'), TO_DATE('2026-05-13', 'YYYY-MM-DD'));

-- === Frontend / UI ===
-- Confirmation messages — Eugenio (Frontend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Estandarizar mensajes de confirmación.', 'done', 'low', 3, 3, 3, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-04', 'YYYY-MM-DD'), TO_DATE('2026-05-04', 'YYYY-MM-DD'));

-- PDF export — Eugenio (Frontend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Exportar KPIs a PDF.', 'done', 'medium', 4, 4, 4, TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- Chart download — Eugenio (Frontend)
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Descargar gráficas como imagen.', 'done', 'low', 4, 4, 4, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

-- === Bot / Assistant (Gael — led bot work in Sprint 2) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Corregir el bot en base a la retroalimentacion', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-06', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Mejorar manejo de errores del asistente.', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-06', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'));

-- === KPI Visual Improvements (Eugenio — Frontend) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Mejora visual de los KPIs', 'done', 'high', 3, 3, 3, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Mejorar organizacion visual de los KPIs', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Verifcar sprint velocity', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Agregar un filtro por proyecto', 'done', 'high', 4, 4, 4, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-11', 'YYYY-MM-DD'));

-- === Linux Courses (each person assigned to their own) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 7, 'Cursos- Linux- Ivanna', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 8, 'Cursos- Linux- Maria Jose', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Cursos- Linux- Gael', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 6, 'Cursos- Linux- Diego I', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 5, 'Cursos- Linux- Diego A', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Cursos- Linux- Eugenio', 'done', 'low', 4, 4, 4, TO_DATE('2026-04-27', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'));

-- === Weekly Meetings (Gael — Scrum Master) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Reunión semanal- 1', 'done', 'medium', 4, 4, 4, TO_DATE('2026-04-30', 'YYYY-MM-DD'), TO_DATE('2026-04-30', 'YYYY-MM-DD'), TO_DATE('2026-04-30', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 9, 'Reunión semanal- 2', 'done', 'medium', 4, 4, 4, TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-08', 'YYYY-MM-DD'), TO_DATE('2026-05-08', 'YYYY-MM-DD'));

-- === Frontend Bug Fixes (Eugenio) ===
INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Arreglar filtrado proyectos', 'done', 'medium', 3, 3, 3, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

INSERT INTO TODOUSER.PROJECT_TASK (SPRINT_ID, PROJECT_ID, ASSIGNEE_ID, TITLE, STATUS, PRIORITY, STORY_POINTS, ESTIMATED_HOURS, ACTUAL_HOURS, START_DATE, EXPECTED_END_DATE, END_DATE)
VALUES (61, 2, 10, 'Arreglar sprint velocity', 'done', 'medium', 3, 3, 3, TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-05-14', 'YYYY-MM-DD'));

COMMIT;
